### ISSUE TITLE
Received "Quandl Error QECx02" when the argument of quandl.get() has special characters

### ISSUE THREAD

**Issue by rsamikan** [quandl/quandl-python#93] opened 2017-09-22 08:46 UTC
I am seeing 

> incorrect Quandl code error

 when the argument of quandl.get() function has special characters.

code snippet:
```
import quandl
mydata = quandl.get("NSE/BAJAJ-AUTO")
```

Issue:

> quandl.errors.quandl_error.NotFoundError: (Status 404) (Quandl Error QECx02) You have submitted an incorrect Quandl code. Please check your Quandl codes and try again.

**Comment by michaelfich** [comment] 2017-09-27 14:58
Hey @rsamikan,

I looked up the NSE database and found the dataset that you were looking for.  I believe your issue is that you have a hyphen where there should be an underscore within the dataset code.  Is this the dataset you are looking for?

https://www.quandl.com/data/NSE/BAJAJ_AUTO-Bajaj-Auto-Limited

The following update to your code should allow you to retrieve data as intended.

```
import quandl
mydata = quandl.get("NSE/BAJAJ_AUTO")
```

I’ll close the issue for now but please feel free to re-open it if you encounter any other issues with this package.

**Closed by michaelfich** 2017-09-27 14:58 UTC

**Comment by Saurabh1602** [comment] 2018-05-25 15:38
I am using a variable to input several databases and trying to merge em. 
df = quandl.get(query, authtoken=api_key)
this is the code but it says get method doesnt exist. please help with this.
