### ISSUE TITLE
Is this dependency correct for more-itertools

### ISSUE THREAD

**Issue by rsheftel** [quandl/quandl-python#141] opened 2019-10-13 04:09 UTC
In setup.py one of the install_requires is "more-itertools <= 5.0.0"

Is that correct that the more-itertools must be LESS than 5.0.0? When installing from conda does not have this constraint. Seems like it should be must at AT LEAST 5.0.0

**Comment by couture-ql** [comment] 2019-11-04 03:47
Hi there,

Yes, the `more-itertools` dependency is awkward and we're currently working on updating our dependencies.  See #137 for more details.  Since this is a duplicate of #137 I'll be closing this in favour of the initial issue.

We'll be updating our library to better deal with our dependencies, and will be keep track of progress over in #137.

**Closed by couture-ql** 2019-11-04 03:47 UTC
